version: "3.1"
services:
  my-db:
    platform: linux/arm64
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=mydb
    ports:
      - 13306:3306
    volumes:
      - /Users/cg6jq7y05g/repository/study/getting-started-docker/docker-compose/data:/var/lib/mysql
    networks:
      - my-network

  my-backend:
    image: junwoo123/catalog-service:v4.0
    environment:
      - spring.datasource.url=jdbc:mariadb://my-db:3306/mydb
      - spring.datasource.password=
    ports:
      - 8088:8088
    depends_on:
      - my-db
    networks:
      - my-network

  my-frontend:
    image: edowon0623/my-frontend:1.0
    ports:
      - 83:80
    depends_on:
      - my-db
    networks:
      - my-network

networks:
  my-network:
    external: true
